### ISSUE TITLE
Getting help

### ISSUE THREAD

**Issue by albfan** [kaushik-rohit/Gnome-todo#1]
Post here related info to your problems

**Comment by kaushik-rohit** [comment]
I am try to create an instance of gtd-provider-todo-txt.c  by calling gtd_provider_todo_txt_new(self-source) inside the gtd-plugin-todo-txt.c.the problem is whenever i include this call the program gets stuck and doesn't proceed further.
The provider class https://github.com/kaushik-rohit/Gnome-todo/blob/Todotxt/plugins/todo-txt/gtd-plugin-todo-txt.c#L194 include a method gtd_provider_todo_txt_new which is being called inside https://github.com/kaushik-rohit/Gnome-todo/blob/Todotxt/plugins/todo-txt/gtd-plugin-todo-txt.c .

**Comment by albfan** [comment]
Is always a good idea to link the commit that resolves this or if it was not resolved with a commit the install, clean, or process you follow to resolve it.
